// <auto-generated />
using Demo_EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo_EF.Migrations
{
    [DbContext(typeof(FDBContext))]
    partial class FDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Demo_EF.FahrzeugEF", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("AktuelleGeschwindigkeit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FZustand")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximalGeschwindigkeit")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Preis")
                        .HasColumnType("REAL");

                    b.HasKey("Name");

                    b.ToTable("Fahrzeuge");
                });
#pragma warning restore 612, 618
        }
    }
}
